Repository GoogleCloudPlatform/netd, pull requests merged in 2019-07, with the labels that each got.

#63 remove noSnat and update the release notes.
  RELEASE.md
  netd.yaml
Labels: approved, lgtm, size/S

#64 Set REGISTRY to gcr.io/gke-release-staging
  Makefile
Labels: size/XS

#65 update Makefile: remove -it from docker args
  Makefile
Labels: size/XS

#66 Limit rp filter loose config only to eth0 interface
  pkg/config/config_policy_routing.go
Labels: approved, lgtm, size/XS

#68 netd shouldn't config masquerade rules.
  netd.yaml
  pkg/config/config_masquerade.go
  pkg/controllers/netconf/network_config_controller.go
  pkg/options/options.go
Labels: approved, lgtm, size/M

#70 netd should config default masq rule when enable_masquerade=true.
  netd.yaml
  scripts/install-cni.sh
Labels: approved, lgtm, size/S
