Repository GoogleCloudPlatform/netd, pull requests merged in 2022-08, with the labels that each got.

#143 Incorporate buildx from GoogleCloudPlatform/netd@cf82473
  Makefile
Labels: lgtm, approved, size/S

#144 Remove iproute2 dependency (using `route` from net-tools instead)
  scripts/Dockerfile.in
  scripts/install-cni.sh
Labels: lgtm, approved, size/S

#145 Replace call to `expr` with bash-builtin operation
  scripts/install-cni.sh
Labels: lgtm, approved, size/XS

#147 Setup IPV6 when node-local stack type label is present
  scripts/install-cni.sh
Labels: lgtm, approved, size/XS

#146 Move netd-init to distroless-iptables with manually added binaries
  Makefile.all
  scripts/Dockerfile.in
  scripts/Makefile
  scripts/alpine-extractor.sh
  scripts/build-jq.sh
  scripts/build-toybox.sh
  scripts/shell-test.sh
  scripts/third_party/static-curl/.ci/Jenkinsfile
  scripts/third_party/static-curl/LICENSE.txt
  scripts/third_party/static-curl/README.md
  scripts/third_party/static-curl/build.sh
  scripts/third_party/static-curl/mykey.asc
Labels: lgtm, approved, size/L

#148 Add comments to scripts/Dockerfile.in
  scripts/Dockerfile.in
Labels: lgtm, approved, size/S

#149 Makefile fixes / improvements
  scripts/Dockerfile.in
  scripts/Makefile
  scripts/alpine-extractor.sh
Labels: lgtm, approved, size/S

#150 Use thockin/go-build-template@6ce4071 instead of buildx-setup in ned-init
  scripts/.gitignore
  scripts/Makefile
Labels: lgtm, approved, size/S

#151 Add .buildx-initialized as a prerequisite of container-%
  scripts/Makefile
Labels: lgtm, approved, size/XS

#152 Revert the attempt to build netd-init in parallel
  Makefile.all
  scripts/Makefile
Labels: lgtm, approved, size/S

#153 Various build fixes and improvements
  scripts/Dockerfile.in
  scripts/Makefile
  scripts/build-jq.sh
  scripts/third_party/static-curl/build.sh
Labels: lgtm, approved, size/M
