Repository GoogleCloudPlatform/netd, pull requests merged in 2022-11, with the labels that each got.

#177 Separate the src_valid_mark sysctl bit from the default configs and add a flag for it.
  cmd/netd/main.go
  pkg/config/config_policy_routing.go
  pkg/controllers/netconf/network_config_controller.go
  pkg/options/options.go
Labels: lgtm, approved, size/M

#178 Allow IPv6 packets on INPUT
  scripts/install-cni.sh
Labels: lgtm, approved, size/S

#179 cleanup ip6tables rules
  scripts/install-cni.sh
Labels: lgtm, approved, size/S

#180 remove confusing comment with typos
  scripts/install-cni.sh
Labels: lgtm, approved, size/XS

#181 Add jingyuanliang to the OWNER file.
  OWNERS
Labels: lgtm, approved, size/XS

#182 add aojea as reviewer
  OWNERS
Labels: lgtm, approved, size/XS
