Repository GoogleCloudPlatform/netd, pull requests merged in 2022-05, with the labels that each got.

#126 Remove the un-used dns-delay script/image.
  scripts/dns-delay/Dockerfile
  scripts/dns-delay/Makefile
  scripts/dns-delay/install-dns-delay.sh
Labels: lgtm, approved, size/M

#130 Add environment variables used by install-cni.sh to netd.yaml
  netd.yaml
Labels: lgtm, approved, size/S

#133 `RUN apt-mark unhold libcap2` in Dockerfile.in
  Dockerfile.in
Labels: lgtm, approved, size/XS

#132 Make ENABLE_PRIVATE_IPV6_ACCESS environment variable optional
  netd.yaml
  scripts/install-cni.sh
Labels: lgtm, approved, size/XS

#131 Allow IPv6 route to be customized with configmap netd-config
  netd.yaml
  scripts/install-cni.sh
Labels: lgtm, approved, size/XS
