Repository GoogleCloudPlatform/netd, pull requests merged in 2023-08, with the labels that each got.

#220 Use curl-healthcheck for cilium to ensure its readiness before writin…
  scripts/install-cni.sh
Labels: lgtm, approved, size/S

#221 Move the wait for Cilium readiness to the end
  scripts/install-cni.sh
Labels: lgtm, approved, size/M

#222 Fix typo in kernel metrics
  pkg/metrics/collector/kernel_metrics.go
Labels: lgtm, approved, size/XS
