Repository GoogleCloudPlatform/netd, pull requests merged in 2024-09, with the labels that each got.

#350 Pick up thockin/go-build-template#116 and thockin/go-build-template#123
  Dockerfile.in
  Makefile
  go.mod
  scripts/Dockerfile.in
  scripts/Makefile
  tools/go.mod
  tools/go.sum
  tools/tools.go
Labels: lgtm, approved, size/XXL

#352 Fix some lint errors and mark nolint and TODO #351 on the rest
  .golangci.yml
  pkg/config/config_test.go
  pkg/metrics/collector/pod_ip_metrics.go
  pkg/metrics/collector/pod_ip_metrics_test.go
Labels: lgtm, approved, size/M

#349 Read CILIUM_CHAINING_MODE env var and use it for cilium-cni config
  scripts/install-cni.sh
  scripts/test-install-cni.sh
  scripts/testcase/testcase-cilium-chaining-v2.sh
  scripts/testcase/testcase-cilium-chaining.sh
  scripts/testdata/expected-cilium-chaining.json
Labels: lgtm, approved, size/L

#354 Update deprecated cache.NewInformer() to cache.NewInformerWithOptions()
  pkg/metrics/collector/netlink_metrics.go
Labels: lgtm, approved, size/S

#356 Remove deprecated MAINTAINER instructions from Dockerfiles
  Dockerfile.in
  scripts/Dockerfile.in
Labels: lgtm, approved, size/XS

#355 Stop dependabot bumps in `/tools`; we routinely sync from upstream
  .github/dependabot.yaml
Labels: lgtm, approved, size/XS

#359 Use protobuf encoding for core K8s APIs in netd
  pkg/metrics/collector/netlink_metrics.go
  pkg/metrics/collector/pod_ip_metrics.go
Labels: lgtm, approved, size/XS

#361 Run `go mod tidy` and `go mod vendor` on the repo
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, size/M

#363 Fix cilium watchdog to write CNI config at least once
  scripts/install-cni.sh
  scripts/testcase/testcase-basic-overwrite.sh
  scripts/testcase/testcase-cilium-overwrite.sh
  scripts/testcase/testcase-watchdog-cilium-faststart-overwrite.sh
  scripts/testcase/testcase-watchdog-cilium-overwrite.sh
  scripts/testcase/testcase-watchdog-overwrite.sh
Labels: lgtm, approved, size/L

#365 Bump base image to distroless-iptables:v0.6.3
  Makefile
  scripts/Makefile
Labels: lgtm, approved, size/XS
