Repository GoogleCloudPlatform/netd, pull requests merged in 2025-04, with the labels that each got.

#422 go get golang.org/x/net@v0.38.0
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/server.go
  vendor/modules.txt
Labels: lgtm, approved, size/M

#421 Skip CNI config writing for any gke-dpv2-unified-cni node label value
  scripts/install-cni.sh
  scripts/testcase/testcase-cilium-skip-any.sh
Labels: approved, size/M

#427 Exempt UDP traffic if an impacted kernel version is detected.
  go.mod
  go.sum
  pkg/config/config_policy_routing.go
  pkg/controllers/netconf/network_config_controller.go
  pkg/kernel/kernel.go
  pkg/kernel/kernel_test.go
  vendor/github.com/pmezard/go-difflib/LICENSE
  vendor/github.com/pmezard/go-difflib/difflib/difflib.go
  vendor/github.com/stretchr/testify/LICENSE
  vendor/github.com/stretchr/testify/assert/assertion_compare.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertion_order.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/doc.go
  vendor/github.com/stretchr/testify/assert/errors.go
  vendor/github.com/stretchr/testify/assert/forward_assertions.go
  vendor/github.com/stretchr/testify/assert/http_assertions.go
  vendor/k8s.io/apimachinery/pkg/util/version/doc.go
  vendor/k8s.io/apimachinery/pkg/util/version/version.go
  vendor/modules.txt
Labels: lgtm, approved, size/XXL

#429 Bump base image to distroless-iptables:v0.6.9
  Makefile
  scripts/Makefile
Labels: lgtm, approved, size/XS
